### ISSUE TITLE
Undefined case, on, off, trans

### ISSUE THREAD

**Issue by jasuarez** [dfeich/org8-wikiexporters#4]
When installing `ox-twiki` through `use-package`and `ox-twiki.el` is compiled, the following warning appears:

~~~
Warning (bytecomp): the following functions are not known to be defined: case, on, off,
    trans
~~~

If later I try to export an Org file to Twiki, I get the following error: `Symbol's function definition is void: on`

I'm using Emacs 27.1.

**Comment by dfeich** [comment]
Fixed. Need to use `cl-case` instead of the alias `case`. I also applied a number of newer style fixes. The package should get available from MELPA within the next few hours.
